File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 1] discards: 🀘🀙🀄🀅🀅🀃🀆 + 🀈'
Arguments: ()
2021-07-15 13:31:20:     [Player 2] draws a tile...
2021-07-15 13:31:22:     [Player 2] discards: 🀇🀘🀑🀚🀡🀛🀠 + 🀏, melds: 🀆🀆🀆 
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-52: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 2] discards: 🀇🀘🀑🀚🀡🀛🀠 + 🀏, melds: 🀆🀆🀆 '
Arguments: ()
2021-07-15 13:31:22:     [Player 3] draws a tile...
2021-07-15 13:31:24:     [Player 3] discards: 🀂🀡🀑🀅🀃🀇🀞 + 🀇
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-52: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 3] discards: 🀂🀡🀑🀅🀃🀇🀞 + 🀇'
Arguments: ()
2021-07-15 13:31:24:
2021-07-15 13:31:24:     [Bot] draws a tile: 🀇🀎🀛🀟🀠🀑🀓🀀🀃🀆 + 🀜 + [🀐🀑🀒]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45-54: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 516, in _handle_draw_tile
    self.both_log(own_hand_str)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] draws a tile: 🀇🀎🀛🀟🀠🀑🀓🀀🀃🀆 + 🀜 + [🀐🀑🀒]'
Arguments: ()
2021-07-15 13:31:25:     [Bot] discards: 🀐🀄🀟🀔🀌🀖🀜🀈 + 🀃
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 41-48: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 540, in _handle_draw_tile       
    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] discards: 🀐🀄🀟🀔🀌🀖🀜🀈 + 🀃'
Arguments: ()
2021-07-15 13:31:25:     [Bot] hand tiles after discarding: 🀇🀎🀛🀜🀟🀠🀑🀓🀀🀆 + [🀐🀑🀒]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 60-69: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 544, in _handle_draw_tile       
    self.both_log(bot_hand_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] hand tiles after discarding: 🀇🀎🀛🀜🀟🀠🀑🀓🀀🀆 + [🀐🀑🀒]'
Arguments: ()
2021-07-15 13:31:25:
2021-07-15 13:31:25:     Remaining tiles: 39
2021-07-15 13:31:25:     --------------------------------------------------
2021-07-15 13:31:25:
2021-07-15 13:31:25:     [Player 1] draws a tile...
2021-07-15 13:31:35:     [Player 1] discards: 🀘🀙🀄🀅🀅🀃🀆🀈 + 🀟
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-53: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 1] discards: 🀘🀙🀄🀅🀅🀃🀆🀈 + 🀟'
Arguments: ()
2021-07-15 13:31:36:     [Player 2] draws a tile...
2021-07-15 13:31:37:     [Player 2] discards: 🀇🀘🀑🀚🀡🀛🀠🀏 + 🀏, melds: 🀆🀆🀆 
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-53: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 2] discards: 🀇🀘🀑🀚🀡🀛🀠🀏 + 🀏, melds: 🀆🀆🀆 '
Arguments: ()
2021-07-15 13:31:37:     [Player 3] draws a tile...
2021-07-15 13:31:38:     [Player 3] discards: 🀂🀡🀑🀅🀃🀇🀞🀇 + 🀁
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-53: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 3] discards: 🀂🀡🀑🀅🀃🀇🀞🀇 + 🀁'
Arguments: ()
2021-07-15 13:31:38:
2021-07-15 13:31:38:     [Bot] draws a tile: 🀇🀎🀛🀜🀟🀠🀑🀓🀀🀆 + 🀚 + [🀐🀑🀒]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45-54: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 516, in _handle_draw_tile       
    self.both_log(own_hand_str)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] draws a tile: 🀇🀎🀛🀜🀟🀠🀑🀓🀀🀆 + 🀚 + [🀐🀑🀒]'
Arguments: ()
2021-07-15 13:31:39:     [Bot] discards: 🀐🀄🀟🀔🀌🀖🀜🀈🀃 + 🀜
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 41-49: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 540, in _handle_draw_tile       
    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] discards: 🀐🀄🀟🀔🀌🀖🀜🀈🀃 + 🀜'
Arguments: ()
2021-07-15 13:31:39:     [Bot] hand tiles after discarding: 🀇🀎🀚🀛🀟🀠🀑🀓🀀🀆 + [🀐🀑🀒]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 60-69: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 544, in _handle_draw_tile       
    self.both_log(bot_hand_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] hand tiles after discarding: 🀇🀎🀚🀛🀟🀠🀑🀓🀀🀆 + [🀐🀑🀒]'
Arguments: ()
2021-07-15 13:31:39:
2021-07-15 13:31:39:     Remaining tiles: 35
2021-07-15 13:31:39:     --------------------------------------------------
2021-07-15 13:31:39:
2021-07-15 13:31:40:     [Player 1] draws a tile...
2021-07-15 13:31:43:     [Player 1] discards: 🀘🀙🀄🀅🀅🀃🀆🀈🀟 + 🀝
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-54: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 1] discards: 🀘🀙🀄🀅🀅🀃🀆🀈🀟 + 🀝'
Arguments: ()
2021-07-15 13:31:43:     [Player 2] draws a tile...
2021-07-15 13:31:44:     [Player 2] discards: 🀇🀘🀑🀚🀡🀛🀠🀏🀏 + 🀐, melds: 🀆🀆🀆 
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-54: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 2] discards: 🀇🀘🀑🀚🀡🀛🀠🀏🀏 + 🀐, melds: 🀆🀆🀆 '
Arguments: ()
2021-07-15 13:31:44:     [Player 3] draws a tile...
2021-07-15 13:31:46:     [Player 3] discards: 🀂🀡🀑🀅🀃🀇🀞🀇🀁 + 🀘
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-54: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 157, in start_game
    res = self._handle_opponent_discard(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 643, in _handle_opponent_discard    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Player 3] discards: 🀂🀡🀑🀅🀃🀇🀞🀇🀁 + 🀘'
Arguments: ()
2021-07-15 13:31:46:
2021-07-15 13:31:46:     [Bot] draws a tile: 🀇🀎🀚🀛🀟🀠🀑🀓🀀🀆 + 🀚 + [🀐🀑🀒]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45-54: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 516, in _handle_draw_tile       
    self.both_log(own_hand_str)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] draws a tile: 🀇🀎🀚🀛🀟🀠🀑🀓🀀🀆 + 🀚 + [🀐🀑🀒]'
Arguments: ()
2021-07-15 13:31:47:     [Bot] discards: 🀐🀄🀟🀔🀌🀖🀜🀈🀃🀜 + 🀎
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 41-50: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 540, in _handle_draw_tile       
    self.both_log(discard_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] discards: 🀐🀄🀟🀔🀌🀖🀜🀈🀃🀜 + 🀎'
Arguments: ()
2021-07-15 13:31:47:     [Bot] hand tiles after discarding: 🀇🀚🀚🀛🀟🀠🀑🀓🀀🀆 + [🀐🀑🀒]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 60-69: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 544, in _handle_draw_tile       
    self.both_log(bot_hand_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    [Bot] hand tiles after discarding: 🀇🀚🀚🀛🀟🀠🀑🀓🀀🀆 + [🀐🀑🀒]'
Arguments: ()
2021-07-15 13:31:47:
2021-07-15 13:31:47:     Remaining tiles: 31
2021-07-15 13:31:47:     --------------------------------------------------
2021-07-15 13:31:47:
2021-07-15 13:31:49:     --------------------------------------------------
2021-07-15 13:31:49: 
2021-07-15 13:31:49:     <AGARI ba="0,0" hai="14,15,21,27,29,51,53,57,59,63,65" m="48683" machi="29" ten="30,1000,0" yaku="18,1" doraHai="30" who="2" fromWho="0" sc="188,-10,250,0,328,10,234,0" owari="178,-32.0,250,5.0,338,44.0,234,-17.0" />     
2021-07-15 13:31:49:     Player 2 wins from player 0's discard 🀎
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f00e' in position 63: character maps to <undefined>      
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 146, in start_game
    '<AGARI' in msg and self._handle_round_end(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 415, in _handle_round_end       
    self.both_log(win_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: "    Player 2 wins from player 0's discard 🀎"
Arguments: ()
2021-07-15 13:31:49:     🀊🀊🀌🀍🀜🀝🀞🀞🀟🀠 +🀆🀆🀆 + 🀎, 1000p
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 25-34: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 146, in start_game
    '<AGARI' in msg and self._handle_round_end(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 424, in _handle_round_end       
    self.both_log(win_tiles_msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 745, in both_log
    self._stream_log(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 738, in _stream_log
    (not self.logger_obj.buffer_mode) and self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    🀊🀊🀌🀍🀜🀝🀞🀞🀟🀠 +🀆🀆🀆 + 🀎, 1000p'
Arguments: ()
2021-07-15 13:31:49:
2021-07-15 13:31:49:     --------------------------------------------------
2021-07-15 13:31:51:     --------------------------------------------------
2021-07-15 13:31:51:     Round end: [MyBot - 新人 - 17800.0, 盆 - 3級 - 25000.0, ゲリピー - 4級 - 33800.0, DEKU - 二段 - 23400.0]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45-46: character maps to <undefined>
Call stack:
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\chenq\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\chenq\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 74, in <module>
    main()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 70, in main
    run_example_ai()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 48, in run_example_ai
    connect_and_play(ai_obj, opponent_class, user, user_name, '0', game_type, logger_obj,drawer)  # play one game
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 164, in start_game
    'owari' in msg and self._handle_final_scores(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 365, in _handle_final_scores    
    self._log('    Round end: {}'.format([self.game_table.bot] + self.game_table.opponents))
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\client\tenhou_client.py", line 741, in _log
    self.logger_obj.add_line(msg)
  File "c:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI\logger\logger_handler.py", line 48, in add_line
    self.lg.info(msg)
Message: '    Round end: [MyBot - 新人 - 17800.0, 盆 - 3級 - 25000.0, ゲリピー - 4級 - 33800.0, DEKU - 二段 - 23400.0]'    
Arguments: ()
2021-07-15 13:31:51:     Game End
2021-07-15 13:31:51:
PS C:\Users\chenq\Desktop\Mahjong\Mahjong AI\MahjongAI> 